apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image: sreekanth45k/cicd-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cicd-app-service
spec:
  selector:
    app: cicd-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

